{% set name = "geoutils" %}
{% set version = "0.0.8" %}

{% set github_url = "https://github.com/GlacioHack/GeoUtils" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: {{ github_url }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cc57490da824806aeec582a821346e781f2e667e3ac161bba0c71425287ce5b1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
      #    - numpy
      #- geopandas
      #- pyproj
      #- rasterio
      #- matplotlib-base
      #- scipy
      #- tqdm
      #- glibc
  run:
    - python >=3.7
    - pip
    - numpy
    - geopandas
    - pyproj
    - rasterio
    - matplotlib-base
    - scipy
    - tqdm

test:
  imports:
    - geoutils

about:
  home: {{ github_url }}
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Set of tools to handle raster and vector data sets in Python.

extra:
  recipe-maintainers:
    - rhugonnet
    - erikmannerfelt
    - adehecq
    - atedstone
