{% set name = "geoutils" %}
{% set version = "0.0.5" %}

{% set github_url = "https://github.com/GlacioHack/GeoUtils" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: {{ github_url }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 907478f33b26a85b68ab13ef1c9dd6f391d6f2c117fc20c7bb3bef6ee1565c9b 

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - numpy
    - geopandas
    - pyproj
    - rasterio
    - matplotlib-base
    - scipy
    - tqdm
  run:
    - python >=3.7
    - pip
    - numpy
    - geopandas
    - pyproj
    - rasterio
    - matplotlib-base
    - scipy
    - tqdm

test:
  imports:
    - geoutils

about:
  home: {{ github_url }}
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Set of tools to handle raster and vector data sets in Python.

extra:
  recipe-maintainers:
    - erikmannerfelt
    - adehecq
    - atedstone
