{% set name = "geoutils" %}
{% set version = "0.0.14" %}

{% set github_url = "https://github.com/GlacioHack/geoutils" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: {{ github_url }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e8c9d8b49a99ac4678876573dc756a5852c3375953329941e3864e72a201da78

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pip
    - numpy
    - geopandas >=0.12.0
    - pyproj
    - rasterio >=1.3.0
    - matplotlib-base
    - scipy
    - tqdm
    - xarray
    - rioxarray

test:
  imports:
    - geoutils

about:
  home: {{ github_url }}
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Analysis and handling of georeferenced rasters and vectors 

extra:
  recipe-maintainers:
    - rhugonnet
    - erikmannerfelt
    - adehecq
    - atedstone
