{% set name = "geoutils" %}
{% set version = "0.0.3" %}

{% set github_url = "https://github.com/GlacioHack/GeoUtils" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: {{ github_url }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ac15a727aecc243c1ce4c60aa7a39eec88568a992f461a0c3267e356fc11f568 

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - numpy
    - geopandas
    - pyproj
    - rasterio
    - matplotlib-base
    - scipy
    - typing-extensions  # [py<=37]
  run:
    - python >=3.7
    - pip
    - numpy
    - geopandas
    - pyproj
    - rasterio
    - matplotlib-base
    - scipy
    - typing-extensions  # [py<=37]

test:
  imports:
    - geoutils

about:
  home: {{ github_url }}
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Set of tools to handle raster and vector data sets in Python.

extra:
  recipe-maintainers:
    - erikmannerfelt
    - adehecq
    - atedstone
