conda_forge_output_validation: true

github:
  # name of the github organization
  user_or_org: GlacioHack
  # repository name, usually filled in automatically
  repo_name: GeoUtils
  # branch name to execute on
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
